### ISSUE TITLE
DOCS: Add `FAQLayout` component

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/thriving-park-documentation#15]
This task adds the `<FAQLayout />` component.

<img width="788" alt="Screen Shot 2022-03-21 at 6 18 25 PM" src="https://user-images.githubusercontent.com/12022922/159372681-5958401e-33a9-4e21-b22e-e0a5a97545ed.png">

This component is the `parent` component for the `<FAQ />` component (See Issue #14). This component should leverage React's use of [composition](https://reactjs.org/docs/composition-vs-inheritance.html) and the `children` prop to wrap a list of `<FAQ />` components. 

The final markup should look something like this:

```
<FAQLayout>
   <FAQ key={1} />
   <FAQ key={2} />
   <FAQ key={3} />
</FAQLayout>
```

**Comment by forsureitsme** [comment]
#17 was merged already and this can be closed
